# -*- coding: utf-8 -*-
"""olamudo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KKeOnSUtSWKu-Mf31LCkeea8OULtq-KP
"""

"""while True:
    personas = int(input('¿Cuántas personas entran a la fiesta? '))

    if personas == -1:
        break

    contador = 0

    while contador < personas:
        contador += 1
        edad = int(input(f'Ingresa la edad de la persona {contador}: '))

        if edad >= 18:
            print('Puede entrar a la fiesta')
        else:
            print('No puede entrar a la fiesta')"""


"""import math

altura = 5
base = 20
hipotenusa = math.sqrt(altura**2 + base**2)
area = (base * altura) / 2

print("La hipotenusa es:", hipotenusa)
print("El área del triángulo rectángulo es:", area)"""

"""mi_cita = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14,15,16]

num = int(input('ingrese la posicion de maria'))

posicion = mi_cita.index(num)

posiciones_hasta = posicion -1

print(f"Posiciones hasta maria es: {posiciones_hasta} cuadras")



pepito = 0

maria = int(input('ingresa las cuadras'))

contador = pepito

while contador < maria :
  print(f"maria esta a: {contador} de distancia de peito en cuadras")
  contador += 1"""

"""columnas = 4
filas = 4

pepito = 1
maria = 16

while pepito < maria:

    fila = (pepito) // columnas
    columna = (pepito) % columnas


    print(f"Visitando fila {fila + 1}, columna {columna + 1}")

    if (fila + 1) == (filas +2) :
      print('se estan amenazANDO')
    else:
      print('no estan amenazados')
    pepito += 1"""

"""olumnas = 4
filas = 4

pepito = 1
maria = 17

while pepito < maria:
    fila = (pepito - 1) // columnas
    columna = (pepito - 1) % columnas

    print(f"Visitando fila {fila + 1}, columna {columna + 1}")

    if (fila + 1) == (filas + 2):
        print('Se están amenazando')
    else:
        print('No están amenazados')
    pepito += 1"""


columnas = 8
filas = 8

torre1 = [2, 3]
torre2 = [5, 3]

fila_torre1, columna_torre1 = torre1
fila_torre2, columna_torre2 = torre2

if fila_torre1 == fila_torre2 or columna_torre1 == columna_torre2:
    print("Las torres se amenazan")
else:
    print("Las torres no se amenazan ")

columnas = 8
filas = 8

arfil1 = [1, 1]
arfil2 = [5, 7]

fila_alfil1, columna_alfil1 = arfil1
fila_alfil2, columna_alfil2 = arfil2

if abs(fila_alfil1 - fila_alfil2) == abs(columna_alfil1 - columna_alfil2):
    print("Los alfiles están en amenaza")
else:
    print("Los alfiles no están en amenaza.")